name: asiri 
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
